# Generated by Django 3.1.7 on 2021-06-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profilepic.png', null=True, upload_to=''),
        ),
    ]
