# Generated by Django 3.1.7 on 2021-06-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210617_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
