# Generated by Django 3.1.7 on 2021-06-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.department'),
        ),
    ]
